[build.env]
passthrough = ["OPENSSL_STATIC", "OPENSSL_VENDORED"]

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y perl make"]

[target.aarch64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y perl make"]