name: Check pull request source branch
on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  check-branches:
    name: pr_dev_only
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "$HEAD_REF" != "dev" ] && [ "$BASE_REF" = "main" ]; then
            echo "Merge requests to main branch are only allowed from dev branch."
            exit 1
          fi
